apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  nfs:
    path: /sniffers-gitlab-etc
    server: 128.49.90.63
  persistentVolumeReclaimPolicy: Retain
